/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hosp.vistaverde.view;

import hosp.vistaverde.bo.EmpleadoBO;
import hosp.vistaverde.cons.Constantes;
import hosp.vistaverde.entity.Empleado;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/**
 *
 * @author henry
 */
public class EmpleadoView extends javax.swing.JFrame {

    /**
     * Creates new form Empleado
     */
    Image icono = new ImageIcon(getClass().getResource("/hosp/vistaverde/images/maleta.png")).getImage();

    public EmpleadoView() {

        setUndecorated(true);
        setIconImage(icono);
        initComponents();
        setSize(1080, 720);
        listarEmpleado();

        //diseño
        bannerSuperior.setBackground(Constantes.naranja);
        bannerSuperior.setOpaque(true);
        fondoAmari.setBackground(Constantes.amarillo);
        fondoAmari.setOpaque(true);
        fondoBlanco.setBackground(Color.white);
        fondoBlanco.setOpaque(true);
        //fin

        setLocationRelativeTo(null);
        //boton transparente
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setFocusPainted(false);
        //fin
    }

    private EmpleadoBO ebo = new EmpleadoBO();

    public void listarEmpleado() {

        tbEmpleado.setForeground(new Color(102, 102, 102));
        ebo.listarEmpleado(tbEmpleado);

        tbEmpleado.getColumnModel().getColumn(0).setPreferredWidth(30);
        tbEmpleado.getColumnModel().getColumn(0).setMaxWidth(35);

        tbEmpleado.getColumnModel().getColumn(1).setPreferredWidth(100);
        tbEmpleado.getColumnModel().getColumn(1).setMaxWidth(200);

        tbEmpleado.getColumnModel().getColumn(2).setPreferredWidth(150);
        tbEmpleado.getColumnModel().getColumn(2).setMaxWidth(250);

        tbEmpleado.getColumnModel().getColumn(3).setPreferredWidth(80);
        tbEmpleado.getColumnModel().getColumn(3).setMaxWidth(100);


//diseño
        JTableHeader header = tbEmpleado.getTableHeader();
        header.getParent().setBackground(Constantes.naranja);
        header.setForeground(Constantes.grisOscuro);
        header.setFont(Constantes.FuenteBerlin);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmpleado = new javax.swing.JTable();
        txtUsuario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnCerrar = new javax.swing.JToggleButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        bannerSuperior = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fondoAmari = new javax.swing.JLabel();
        fondoBlanco = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(70, 70, 70));
        jLabel4.setText("FORMULARIO EMPLEADO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 70, 370, 30);

        tbEmpleado.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        tbEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbEmpleado.setAutoscrolls(false);
        tbEmpleado.setGridColor(new java.awt.Color(255, 255, 255));
        tbEmpleado.setSelectionBackground(new java.awt.Color(255, 173, 0));
        tbEmpleado.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tbEmpleado);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(560, 100, 480, 570);

        txtUsuario.setBackground(java.awt.Color.white);
        txtUsuario.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 20)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(221, 229, 233)));
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(210, 310, 280, 40);

        txtNombre.setBackground(java.awt.Color.white);
        txtNombre.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 20)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(221, 229, 233)));
        getContentPane().add(txtNombre);
        txtNombre.setBounds(210, 170, 280, 40);

        txtApellido.setBackground(java.awt.Color.white);
        txtApellido.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 20)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(102, 102, 102));
        txtApellido.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(221, 229, 233)));
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(txtApellido);
        txtApellido.setBounds(210, 240, 280, 40);

        txtPassword.setBackground(java.awt.Color.white);
        txtPassword.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(102, 102, 102));
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(221, 229, 233)));
        getContentPane().add(txtPassword);
        txtPassword.setBounds(210, 380, 280, 40);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hosp/vistaverde/images/X.png"))); // NOI18N
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar);
        btnCerrar.setBounds(1060, 0, 20, 20);

        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hosp/vistaverde/images/btnEliminar.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setOpaque(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(380, 530, 140, 40);

        btnModificar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hosp/vistaverde/images/btnModificar.png"))); // NOI18N
        btnModificar.setBorder(null);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.setOpaque(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(230, 530, 140, 40);

        btnAgregar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hosp/vistaverde/images/bbtnAgregar.png"))); // NOI18N
        btnAgregar.setBorder(null);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setOpaque(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(80, 530, 140, 40);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Contraseña");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 380, 114, 27);

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Usuario");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 310, 120, 27);

        txtId.setBackground(java.awt.Color.white);
        txtId.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtId.setForeground(new java.awt.Color(102, 102, 102));
        txtId.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(221, 229, 233)));
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtId);
        txtId.setBounds(830, 70, 128, 24);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hosp/vistaverde/images/btnBuscar.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setOpaque(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(970, 70, 63, 25);
        getContentPane().add(bannerSuperior);
        bannerSuperior.setBounds(0, 0, 1080, 20);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Nombres");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 170, 120, 27);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Apellidos");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 240, 120, 27);

        fondoAmari.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        getContentPane().add(fondoAmari);
        fondoAmari.setBounds(540, 60, 520, 630);
        getContentPane().add(fondoBlanco);
        fondoBlanco.setBounds(0, 20, 1080, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        cerrar();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bannerSuperior;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JToggleButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel fondoAmari;
    private javax.swing.JLabel fondoBlanco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbEmpleado;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    Principal p = new Principal();
    Empleado emp = new Empleado();

    private void cerrar() {
        p.setLocationRelativeTo(null);
        p.setVisible(true);
        this.dispose();
    }

    private void agregar() {

        try {
            String nombres = txtNombre.getText();
            String apellidos = txtApellido.getText();
            String password = txtPassword.getText();
            String usuario = txtUsuario.getText();

            if (usuario.length() > 3 && password.length() > 3 && nombres.length() > 3 && apellidos.length() > 3) {
                emp.setNombres(nombres.toUpperCase());
                emp.setApellidos(apellidos.toUpperCase());
                emp.setUsuario(usuario.toLowerCase());
                emp.setPassword(password);

                ebo.agregarEmpleado(emp);

                listarEmpleado();
            } else {
                JOptionPane.showMessageDialog(null, "NO SE PUDO GUARDAR EL NUEVO USUARIO"
                        + '\n' + "REVISE LOS DATOS");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "NO SE PUDO GUARDAR EL NUEVO USUARIO"
                    + '\n' + "REVISE LOS DATOS");
        }

    }

    private void buscar() {
        try {
            String id = txtId.getText();
            emp.setIdEmpleado(Integer.parseInt(id));
            String[] datos = new String[4];
            datos = ebo.buscarEmpleado(emp).split("#");

            txtNombre.setText(datos[0]);
            txtApellido.setText(datos[1]);
            txtUsuario.setText(datos[2]);
            txtPassword.setText(datos[3]);

        } catch (Exception e) {
        }
    }

    private void modificar() {

        try {
            String nombres = txtNombre.getText();
            String apellidos = txtApellido.getText();
            String password = txtPassword.getText();
            String usuario = txtUsuario.getText();
            int id = Integer.parseInt(txtId.getText());

            if (usuario.length() > 3 && password.length() > 3 && nombres.length() > 3 && apellidos.length() > 3 && id > 0) {
                emp.setNombres(nombres.toUpperCase());
                emp.setApellidos(apellidos.toUpperCase());
                emp.setUsuario(usuario.toLowerCase());
                emp.setPassword(password);
                emp.setIdEmpleado(id);

                ebo.modificarEmpleado(emp);

                listarEmpleado();
                JOptionPane.showMessageDialog(null, "EMPLEADO MODIFICADO CORRECTAMENTE");
            } else {
                JOptionPane.showMessageDialog(null, "NO SE PUDO MODIFICAR USUARIO"
                        + '\n' + "REVISE LOS DATOS");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "NO SE PUDO MODIFICAR USUARIO"
                    + '\n' + "REVISE LOS DATOS");
        }
    }

    private void eliminar() {

        try {
            int id = Integer.parseInt(txtId.getText());

            if (id > 0) {
                emp.setIdEmpleado(id);
                ebo.eliminarEmpleado(id);

                listarEmpleado();
            } else {
                JOptionPane.showMessageDialog(null, "NO SE PUDO MODIFICAR USUARIO"
                        + '\n' + "REVISE LOS DATOS");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "NO SE PUDO MODIFICAR USUARIO"
                    + '\n' + "REVISE LOS DATOS");
        }

    }

}
