/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hosp.vistaverde.view;

import hosp.vistaverde.bo.ClienteBO;
import hosp.vistaverde.cons.Constantes;
import hosp.vistaverde.entity.Cliente;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/**
 *
 * @author henry
 */
public class GananciasView extends javax.swing.JFrame {

    /**
     * Creates new form GananciasView
     */
    Image icono = new ImageIcon(getClass().getResource("/hosp/vistaverde/images/maleta.png")).getImage();
    ClienteBO cbo = new ClienteBO();

    public GananciasView() {

        setUndecorated(true);
        initComponents();
        setSize(1080, 720);
        diseño();

        listarClientes();
    }

    private void listarClientes() {

        String fecha;
        if (cboMes.getSelectedIndex() < 10) {
            fecha = "00/0" + (cboMes.getSelectedIndex() + 1) + "/" + cboYear.getSelectedItem();
        } else {
            fecha = "00/" +cboMes.getSelectedIndex() + "/" + "2020";
        }
        
        //centra los datos
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        //

        txtGanancias.setText(cbo.listarClienteFecha(tbClientes, fecha) + "0");

        tbClientes.getColumnModel().getColumn(0).setPreferredWidth(35);
        tbClientes.getColumnModel().getColumn(0).setMaxWidth(40);

        tbClientes.getColumnModel().getColumn(1).setPreferredWidth(300);
        tbClientes.getColumnModel().getColumn(1).setMaxWidth(350);

        tbClientes.getColumnModel().getColumn(2).setPreferredWidth(300);
        tbClientes.getColumnModel().getColumn(2).setMaxWidth(350);

        tbClientes.getColumnModel().getColumn(3).setPreferredWidth(100);
        tbClientes.getColumnModel().getColumn(3).setMaxWidth(100);

        tbClientes.getColumnModel().getColumn(4).setPreferredWidth(100);
        tbClientes.getColumnModel().getColumn(4).setMaxWidth(100);
        tbClientes.getColumnModel().getColumn(4).setMinWidth(100);

        tbClientes.getColumnModel().getColumn(5).setPreferredWidth(50);
        tbClientes.getColumnModel().getColumn(5).setMaxWidth(40);
        tbClientes.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);

        tbClientes.getColumnModel().getColumn(6).setPreferredWidth(60);
        tbClientes.getColumnModel().getColumn(6).setMaxWidth(70);
        tbClientes.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);

        //diseño
        JTableHeader header = tbClientes.getTableHeader();
        header.getParent().setBackground(Constantes.naranja);
        header.setForeground(Constantes.grisOscuro);
        header.setFont(Constantes.FuenteBerlin);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        cboMes = new javax.swing.JComboBox<>();
        cboYear = new javax.swing.JComboBox<>();
        btnCerrar = new javax.swing.JButton();
        txtGanancias = new javax.swing.JTextField();
        banner = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        fondoAmarillo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tbClientes.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbClientes.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tbClientes);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 190, 1040, 510);

        cboMes.setBackground(new java.awt.Color(245, 248, 249));
        cboMes.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        cboMes.setForeground(new java.awt.Color(102, 102, 102));
        cboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENERO", "FEBRERO", "MARSO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO ", "SETIEMBRE", "OCTUBRE ", "NOBIEMBRE", "DICIEMBRE" }));
        cboMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMesActionPerformed(evt);
            }
        });
        getContentPane().add(cboMes);
        cboMes.setBounds(20, 130, 200, 37);

        cboYear.setBackground(new java.awt.Color(245, 248, 249));
        cboYear.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        cboYear.setForeground(new java.awt.Color(102, 102, 102));
        cboYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024", "2025", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2035", "2036", "2037", "2038", "2039", "2040", " " }));
        cboYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboYearActionPerformed(evt);
            }
        });
        getContentPane().add(cboYear);
        cboYear.setBounds(240, 130, 100, 37);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hosp/vistaverde/images/X.png"))); // NOI18N
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar);
        btnCerrar.setBounds(1060, 0, 20, 20);

        txtGanancias.setEditable(false);
        txtGanancias.setBackground(new java.awt.Color(245, 248, 249));
        txtGanancias.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        txtGanancias.setForeground(new java.awt.Color(102, 102, 102));
        txtGanancias.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(221, 229, 233)));
        txtGanancias.setCaretColor(new java.awt.Color(51, 51, 51));
        txtGanancias.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtGanancias.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtGanancias.setOpaque(false);
        txtGanancias.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtGanancias);
        txtGanancias.setBounds(910, 140, 150, 40);
        getContentPane().add(banner);
        banner.setBounds(0, 0, 1080, 20);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 48)); // NOI18N
        jLabel1.setText("Ganancias");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 30, 290, 40);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hosp/vistaverde/images/logopeque.png"))); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(20, 40, 240, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hosp/vistaverde/images/bolsa-de-dinero.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(860, 140, 30, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hosp/vistaverde/images/dinero.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(650, 30, 110, 60);
        getContentPane().add(fondo);
        fondo.setBounds(0, 110, 1080, 610);
        getContentPane().add(fondoAmarillo);
        fondoAmarillo.setBounds(0, 20, 1080, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMesActionPerformed
        listarClientes();
    }//GEN-LAST:event_cboMesActionPerformed

    private void cboYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboYearActionPerformed
        listarClientes();
    }//GEN-LAST:event_cboYearActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        cerrar();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JComboBox<String> cboMes;
    private javax.swing.JComboBox<String> cboYear;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondoAmarillo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logo;
    private javax.swing.JTable tbClientes;
    private javax.swing.JTextField txtGanancias;
    // End of variables declaration//GEN-END:variables

    Principal p = new Principal();

    private void diseño() {

        setLocationRelativeTo(null);
        setIconImage(icono);
        //boton transparente
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setFocusPainted(false);

        //
        banner.setBackground(Constantes.naranja);
        banner.setOpaque(true);
        fondo.setBackground(Color.white);
        fondo.setOpaque(true);
        fondoAmarillo.setBackground(Constantes.amarillo);
        fondoAmarillo.setOpaque(true);
    }

    private void cerrar() {
        p.setLocationRelativeTo(null);
        p.setVisible(true);
        dispose();
    }

}
