/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hosp.vistaverde.view;

import hosp.vistaverde.bo.ClienteBO;
import hosp.vistaverde.cons.Constantes;
import hosp.vistaverde.entity.Cliente;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/**
 *
 * @author henry
 */
public class RegistroView extends javax.swing.JFrame {

    /**
     * Creates new form Registrar
     */
    Cliente c = new Cliente();
    Image icono = new ImageIcon(getClass().getResource("/hosp/vistaverde/images/maleta.png")).getImage();

    public RegistroView() {

        setSize(1080, 720);
        setUndecorated(true);
        initComponents();
        diseño();
        listarClientes();

    }

    private void listarClientes() {
        cbo.listarCliente(tbClientes);

        tbClientes.getColumnModel().getColumn(0).setPreferredWidth(35);
        tbClientes.getColumnModel().getColumn(0).setMaxWidth(40);

        tbClientes.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbClientes.getColumnModel().getColumn(1).setMaxWidth(165);

        tbClientes.getColumnModel().getColumn(2).setPreferredWidth(150);
        tbClientes.getColumnModel().getColumn(2).setMaxWidth(165);

        tbClientes.getColumnModel().getColumn(3).setPreferredWidth(70);
        tbClientes.getColumnModel().getColumn(3).setMaxWidth(70);

        tbClientes.getColumnModel().getColumn(4).setPreferredWidth(70);
        tbClientes.getColumnModel().getColumn(4).setMaxWidth(70);
        tbClientes.getColumnModel().getColumn(4).setMinWidth(70);

        tbClientes.getColumnModel().getColumn(5).setPreferredWidth(30);
        tbClientes.getColumnModel().getColumn(5).setMaxWidth(40);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tbClientes.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
        //diseño

        JTableHeader header = tbClientes.getTableHeader();
        header.getParent().setBackground(Constantes.naranja);
        header.setForeground(Constantes.grisOscuro);
        header.setFont(Constantes.FuenteBerlin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollBar1 = new javax.swing.JScrollBar();
        txtHora = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboHabitacion = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtDias = new javax.swing.JTextField();
        txtProsedencia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        btnCerrar = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        logo = new javax.swing.JLabel();
        fondoAmarillo = new javax.swing.JLabel();
        bannerSuperior = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        txtHora.setEditable(false);
        txtHora.setBackground(new java.awt.Color(245, 248, 249));
        txtHora.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 20)); // NOI18N
        txtHora.setForeground(new java.awt.Color(102, 102, 102));
        txtHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHora.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(221, 229, 233)));
        txtHora.setCaretColor(new java.awt.Color(102, 102, 102));
        txtHora.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtHora.setMargin(new java.awt.Insets(4, 4, 4, 4));
        getContentPane().add(txtHora);
        txtHora.setBounds(400, 400, 80, 40);

        txtDni.setBackground(new java.awt.Color(245, 248, 249));
        txtDni.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 20)); // NOI18N
        txtDni.setForeground(new java.awt.Color(102, 102, 102));
        txtDni.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(221, 229, 233)));
        txtDni.setCaretColor(new java.awt.Color(102, 102, 102));
        txtDni.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });
        getContentPane().add(txtDni);
        txtDni.setBounds(170, 330, 130, 40);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Habitacion");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 490, 90, 21);

        txtPrecio.setEditable(false);
        txtPrecio.setBackground(new java.awt.Color(245, 248, 249));
        txtPrecio.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 20)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(102, 102, 102));
        txtPrecio.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(221, 229, 233)));
        txtPrecio.setCaretColor(new java.awt.Color(102, 102, 102));
        txtPrecio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txtPrecio);
        txtPrecio.setBounds(400, 560, 75, 40);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Prosedencia");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 270, 110, 21);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("DNI");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 340, 40, 21);

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Dias");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 570, 50, 21);

        cboHabitacion.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        cboHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "N° 01", "N° 02", "N° 03", "N° 04", "N° 05", "N° 06", "N° 07", "N° 08", "N° 09", "N° 10" }));
        cboHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboHabitacionActionPerformed(evt);
            }
        });
        getContentPane().add(cboHabitacion);
        cboHabitacion.setBounds(170, 480, 310, 37);

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Precio S/.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(270, 570, 90, 21);

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(75, 75, 75));
        jLabel10.setText("ID");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(890, 70, 30, 20);

        btnBuscar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hosp/vistaverde/images/btnBuscar.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setOpaque(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(1000, 70, 60, 20);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Fecha");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 410, 60, 21);

        txtFecha.setEditable(false);
        txtFecha.setBackground(new java.awt.Color(245, 248, 249));
        txtFecha.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 20)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(102, 102, 102));
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(221, 229, 233)));
        txtFecha.setCaretColor(new java.awt.Color(102, 102, 102));
        txtFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtFecha.setMargin(new java.awt.Insets(4, 4, 4, 4));
        getContentPane().add(txtFecha);
        txtFecha.setBounds(170, 400, 130, 40);

        txtId.setBackground(new java.awt.Color(245, 248, 249));
        txtId.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 20)); // NOI18N
        txtId.setForeground(new java.awt.Color(102, 102, 102));
        txtId.setToolTipText("ID");
        txtId.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(221, 229, 233)));
        txtId.setCaretColor(new java.awt.Color(102, 102, 102));
        getContentPane().add(txtId);
        txtId.setBounds(920, 70, 70, 20);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Hora");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 410, 50, 21);

        txtApellido.setBackground(new java.awt.Color(245, 248, 249));
        txtApellido.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 20)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(102, 102, 102));
        txtApellido.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(221, 229, 233)));
        txtApellido.setCaretColor(new java.awt.Color(102, 102, 102));
        txtApellido.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(txtApellido);
        txtApellido.setBounds(170, 190, 310, 40);

        txtDias.setBackground(new java.awt.Color(245, 248, 249));
        txtDias.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 20)); // NOI18N
        txtDias.setForeground(new java.awt.Color(102, 102, 102));
        txtDias.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(221, 229, 233)));
        txtDias.setCaretColor(new java.awt.Color(102, 102, 102));
        txtDias.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txtDias);
        txtDias.setBounds(170, 560, 60, 40);

        txtProsedencia.setBackground(new java.awt.Color(245, 248, 249));
        txtProsedencia.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 20)); // NOI18N
        txtProsedencia.setForeground(new java.awt.Color(102, 102, 102));
        txtProsedencia.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(221, 229, 233)));
        txtProsedencia.setCaretColor(new java.awt.Color(102, 102, 102));
        txtProsedencia.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txtProsedencia);
        txtProsedencia.setBounds(170, 260, 310, 40);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Apellidos");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 200, 90, 21);

        jToggleButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hosp/vistaverde/images/btnEliminar.png"))); // NOI18N
        jToggleButton1.setBorder(null);
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.setOpaque(false);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(340, 660, 140, 40);

        txtNombre.setBackground(new java.awt.Color(245, 248, 249));
        txtNombre.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 20)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(221, 229, 233)));
        txtNombre.setCaretColor(new java.awt.Color(102, 102, 102));
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txtNombre);
        txtNombre.setBounds(170, 120, 310, 40);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Nombres");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 130, 80, 21);

        jToggleButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hosp/vistaverde/images/btnModificar2.png"))); // NOI18N
        jToggleButton2.setBorder(null);
        jToggleButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton2.setOpaque(false);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(50, 660, 140, 40);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hosp/vistaverde/images/X.png"))); // NOI18N
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar);
        btnCerrar.setBounds(1060, 0, 20, 20);

        tbClientes.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbClientes.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tbClientes);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(533, 100, 530, 600);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hosp/vistaverde/images/logopeque.png"))); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(10, 40, 240, 40);
        getContentPane().add(fondoAmarillo);
        fondoAmarillo.setBounds(0, 20, 1080, 80);
        getContentPane().add(bannerSuperior);
        bannerSuperior.setBounds(0, 0, 1080, 20);
        getContentPane().add(fondo);
        fondo.setBounds(0, 100, 1080, 630);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        cerrar();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        modificar();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        eliminar();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void cboHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboHabitacionActionPerformed
        precios();
    }//GEN-LAST:event_cboHabitacionActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bannerSuperior;
    private javax.swing.JToggleButton btnBuscar;
    private javax.swing.JToggleButton btnCerrar;
    private javax.swing.JComboBox<String> cboHabitacion;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondoAmarillo;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel logo;
    private javax.swing.JTable tbClientes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProsedencia;
    // End of variables declaration//GEN-END:variables

    Principal p = new Principal();
    ClienteBO cbo = new ClienteBO();

    private float precioD;

    private void precios() {

        int cuarto = cboHabitacion.getSelectedIndex();

        switch (cuarto) {
            case 1:
                precioD = 15;
                txtPrecio.setText("" + precioD);
                break;
            case 2:
                precioD = 15;
                txtPrecio.setText("" + precioD);
                break;
            case 3:
                precioD = 20;
                txtPrecio.setText("" + precioD);
                break;
            case 4:
                precioD = 15;
                txtPrecio.setText("" + precioD);
                break;
            case 5:
                precioD = 20;
                txtPrecio.setText("" + precioD);
                break;
            case 6:
                precioD = 15;
                txtPrecio.setText("" + precioD);
                break;
            case 7:
                precioD = 15;
                txtPrecio.setText("" + precioD);
                break;
            case 8:
                precioD = 15;
                txtPrecio.setText("" + precioD);
                break;
            case 9:
                precioD = 15;
                txtPrecio.setText("" + precioD);
                break;
            case 10:
                precioD = 20;
                txtPrecio.setText("" + precioD);
                break;
            default:
                txtPrecio.setText("");

        }

    }

    private void cerrar() {
        p.setLocationRelativeTo(null);
        p.setVisible(true);
        dispose();
    }

    private void buscar() {
        try {
            int id = Integer.parseInt(txtId.getText());
            c.setId(id);
            String[] datos = new String[9];
            datos = cbo.buscarCliente(c).split("#");
            if (!datos[0].equals("")) {
                txtNombre.setText(datos[0]);
                txtApellido.setText(datos[1]);
                txtDni.setText(datos[2]);
                txtProsedencia.setText(datos[3]);
                txtFecha.setText(datos[4]);
                txtHora.setText(datos[5]);
                cboHabitacion.setSelectedIndex(Integer.parseInt(datos[6]));
                precios();
                txtDias.setText(datos[7]);

            } else {
                JOptionPane.showMessageDialog(null, "NO SE ENCONTRO CLIENTE");
                limpiar();
            }

        } catch (Exception e) {
        }
    }

    private void modificar() {
        try {
            int noches = Integer.parseInt(txtDias.getText());
            float precioT = precioD * noches;
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String dni = txtDni.getText();
            String prosedencia = txtProsedencia.getText();
            String Fecha = txtFecha.getText();
            String Hora = txtHora.getText();
            int dias = Integer.parseInt(txtDias.getText());
            String cuarto = "" + cboHabitacion.getSelectedIndex();

            if (cboHabitacion.getSelectedIndex() > 0 && precioT > 0 && !txtApellido.getText().isEmpty()
                    && txtDni.getText().length() == 8 && !txtNombre.getText().isEmpty()
                    && !txtProsedencia.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "MODIFICADO CORRECTAMENTE");

                precioT = precioD * dias;

                c.setNombre(nombre);
                c.setApellidos(apellido);
                c.setCostoTotal(precioT);
                c.setDni(dni);
                c.setProsedencia(prosedencia);
                c.setCuarto(cuarto);
                c.setFecha(Fecha);
                c.setHora(Hora);
                c.setCostoTotal(precioT);
                c.setDias(dias);

                cbo.modificarCliente(c);

                listarClientes();

            } else {
                JOptionPane.showMessageDialog(null, "No se pudo completar, revise todos los datos");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo completar, revise todos los datos");
        }
    }

    private void eliminar() {
        try {
            cbo.eliminarCliente(Integer.parseInt(txtId.getText()));
            listarClientes();
            limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "NO SE ENCONTRO EL CLIENTE");
        }

    }

    private void limpiar() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtDni.setText("");
        txtProsedencia.setText("");
        txtFecha.setText("");
        txtHora.setText("");
        cboHabitacion.setSelectedIndex(0);
        precios();
        txtDias.setText("");
        txtId.setText("");

    }

    private void diseño() {
        setLocationRelativeTo(null);
        setIconImage(icono);
        //boton transparente
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setFocusPainted(false);
        //
        bannerSuperior.setBackground(Constantes.naranja);
        bannerSuperior.setOpaque(true);
        fondo.setBackground(Color.white);
        fondo.setOpaque(true);
        fondoAmarillo.setBackground(Constantes.amarillo);
        fondoAmarillo.setOpaque(true);
    }

      private void teclaEnCboHabitacion() {

        cboHabitacion.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent ke) {

            }

            @Override
            public void keyPressed(KeyEvent ke) {

            }

            @Override
            public void keyReleased(KeyEvent ke) {
                if (ke.getKeyCode() == KeyEvent.VK_ENTER) {
                    modificar();
                }
            }
        });

    }

    
}
